# Generated by Django 5.0.6 on 2024-06-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('cliente', models.CharField(max_length=50)),
                ('productosVendidos', models.CharField(max_length=50)),
                ('numBoleta', models.IntegerField()),
            ],
        ),
    ]
