# Generated by Django 5.0.6 on 2024-06-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoEntrega', models.CharField(max_length=100)),
                ('Valor', models.IntegerField()),
                ('courier', models.CharField(max_length=100)),
                ('articulos', models.IntegerField()),
            ],
        ),
    ]
