# Generated by Django 5.0.6 on 2024-06-27 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPago', models.CharField(max_length=100)),
                ('TotalCompra', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.boleta')),
            ],
        ),
    ]
