# Generated by Django 5.0.6 on 2024-05-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
