# Generated by Django 5.0.6 on 2024-05-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='producto',
            new_name='herramienta',
        ),
    ]
